### ISSUE TITLE
Add React and basic libraries

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#1]
This project was discussed with the team and we decided will be a react PWA but we don't need granular control (for now at least). Also as the primary target stated by Dasher is mobile, we decided to add PWA support.

To start on the shoulder of giants we decided to try [the template available in CRA for PWA](https://create-react-app.dev/docs/making-a-progressive-web-app/) and concentrate on business logic instead.

## Checklist

- [ ] App have `react` at least v17.
- [ ] Add `react-router` with support for hooks
- [ ] Add `styled-component` support

## Related discussions

- https://github.com/Azordev/dasher-user/discussions/7
- https://github.com/Azordev/dasher-user/discussions/9

**Comment by coder-jkb** [comment]
Can you please describe, giving more details

**Comment by Israel-Laguan** [comment]
> Can you please describe, giving more details

Description updated! Please check!

**Comment by AlejandroSalcido** [comment]
I think the current listed libraries are great for the project, i would suggest adding react-icons in a future.

**Comment by Israel-Laguan** [comment]
That would depend on current design using those icons but will take that into account, thanks for the suggestion

**Comment by Israel-Laguan** [comment]
We decided in a meeting with @Saikilito and @denisosuna not to use tests in this project
