### ISSUE TITLE
Define CSS library

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#10]
We can use default CSS but we can opt-in to any good CSS solution for React. Some options are:

- CSS styling and CSS modules (default)
- SASS/SCSS (would need compiler in the pipeline)
- Ready-made library like Bootstrap or Material UI
- styled-components
- Something else

Until now team decided on styled-components but needs validation

Depends on #1

**Comment by AlejandroSalcido** [comment]
I would go with styled components. due its usability and structured way to work, also is very easy to change values working that way

**Comment by denisosuna** [comment]
we will work with styled-components

**Comment by Israel-Laguan** [comment]
So styled-component is the one! Thanks !
