### ISSUE TITLE
Error Boundary is not catching errors

### ISSUE THREAD

**Issue by denisosuna** [Azordev/dasher-user#104]
**Describe the bug**

Error Boundary is not catching errors 

**To Reproduce**

**Expected behavior**

Error boundary must send an error to DB and redirect to error page

**Comment by heliomar-pena** [comment]
@Israel-Laguan @e-azocar @denisosuna this is already complete? i think that in #146

**Comment by denisosuna** [comment]
@Katsu08 this was completed in that issue, although still, we needed to check the function to insert the errors

**Comment by Israel-Laguan** [comment]
> @Israel-Laguan @e-azocar @denisosuna this is already complete? i think that in #146

we need to test and verify it works as expected. I remember it was catching certain errors but not sending anything to DB. At least we have to send errors to DB

**Comment by heliomar-pena** [comment]
@e-azocar Please check if this issue is already done. I remember that we only need check if is complete

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
