### ISSUE TITLE
Home Page in Desktop mode doesn't looks like the design

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#116]
**Describe the bug**
The home page doesn't looks how the design

**To Reproduce**
Go to https://dev--azordev-dasher-user.netlify.app/

**Expected behavior**
I have listed the bugs here

- [ ] 1. The **Dasher Guy** image should be in the bottom of the page and not at start. I have see that exists an effort for move to up the image (`margin-top: -23%`). Maybe this style of margin-top is for the mobile and we forgot to remove it on desktop. (Please check screenshot 1)

- [ ] 2. The "Hola!" text should be more big, in Mobile looks good, but in desktop is not according to the design. (Please check screenshot 2). Please add a [media query](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) to increment the font size in desktop.

- [ ] 3. At desktop device, the "Hola!" text and their paragraph should be aligned to the left (Please check image 3). Please change `text-align: center` for `text-align: left` and add margin / padding to separate it for the borders

- [ ] 4. The "Hola!" text and the button "Aceptar" have very much space between. This can be solved? (Please check image 4)

**Screenshots**
1. Dasher Guy is at the start of the page instead of the bottom
**Actually is:**
![imagen](https://user-images.githubusercontent.com/66505715/139719386-c04ed37a-04ae-42a8-9e80-27e05391d5b8.png)
**Expected:** (Note that the guy is at the left-bottom corner of the page, and not have margin bottom or left to separate it from the borders)
![imagen](https://user-images.githubusercontent.com/66505715/139719457-f2dae5c2-ae0e-4317-ae84-2b69a4de46f1.png)
I have notice this effort for move up the image, can be an error?:
![imagen](https://user-images.githubusercontent.com/66505715/139716968-789f9ca3-73b6-4857-8833-483d03f32ac8.png)
2. "Hola" text is some little in desktop 
**Actually is:**
![imagen](https://user-images.githubusercontent.com/66505715/139718775-9e67b369-5873-4bf5-84fe-7e71cf055b82.png) | 
**Expected:**
![imagen](https://user-images.githubusercontent.com/66505715/139718844-5a9301fa-0cb7-4fea-a4b2-d047452716fa.png) |
3. "Hola!" text and paragraph should be aligned to the left
**Actually is:**
![imagen](https://user-images.githubusercontent.com/66505715/139718702-4d7a40d2-4c96-4915-a574-b201e1c4721e.png)
**Expected:**
![imagen](https://user-images.githubusercontent.com/66505715/139718617-0fb23474-6c72-4ead-9668-19186b2e8d82.png)
4. The button "aceptar" is very separated of the rest
![imagen](https://user-images.githubusercontent.com/66505715/139718775-9e67b369-5873-4bf5-84fe-7e71cf055b82.png) |

**Comment by Saikilito** [comment]
Hi, I want to point out that although the design is made that way I notice a mistake in leaving the image of the dasher depending on the edges of any screen, due to the dynamic behavior of the spaces on the screen we leave many empty places and also complicates the layout of the web, this is valid for any page that wants to depend on images of edges.

I sincerely think that centering the image is the right choice.

![image](https://user-images.githubusercontent.com/29690711/140929311-71dd2e76-421b-4fab-8de0-3bb60b3b3f96.png)

**Comment by Israel-Laguan** [comment]
> I sincerely think that centering the image is the right choice.
> 
Yeah, I agree, centering the image is better
