### ISSUE TITLE
Check Page in Mobile mode doesn't looks like the design

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#117]
**Describe the bug**
I have checked and check view is not showing how in the desktop

**To Reproduce**
Go to https://dev--azordev-dasher-user.netlify.app/check

**Expected behavior**
I have listed the bugs here.

1. Header need more horizontal (<-  ->) padding. (Check screenshot 1)
2. Text "Hola!" "Ingresa tu numero de boleta" have very space between. This is because `<h1></h1>` and `<p></p>` have a default line height, you can solve it modifying this property with CSS. [Click here to see an example](https://www.w3schools.com/cssref/tryit.asp?filename=trycss_line-height). (Check screenshot 2)
3. Once you have erase the height to the header text, you will notice that doesn't exists space between the hand image and the text, please add a little of margin. (Check screenshot 3)
4. The input should be flat, actually it have shadows. (Check screenshot 4)
5. The form is not center (The input, input label and button is more for the left). (Check screenshot 5)

**Screenshots**
1. Header need more horizontal spacing
Actually is:
![imagen](https://user-images.githubusercontent.com/66505715/139727646-c9c3deec-ad2a-490b-874e-14afee691f0f.png)
Should be:
![imagen](https://user-images.githubusercontent.com/66505715/139727664-b1f44570-0130-4fb4-9447-7f6e77601c8b.png)
2. Text "Hola" and "Ingresa tu numero de boleta" have very space between
Actually is:
![imagen](https://user-images.githubusercontent.com/66505715/139727736-10252b6d-40af-4011-ae59-26222a1f0bd9.png)
Should be:
![imagen](https://user-images.githubusercontent.com/66505715/139727753-3c188125-759f-41de-99ed-3c538865e50c.png)
3. Hand image and text doesn't have space between, please add a little more
![imagen](https://user-images.githubusercontent.com/66505715/139728550-ee3eaa07-30be-4742-acf2-707b69c39c49.png)
4. The input should be flat, please remove shadows and add border gray or move to up the shadow to create this effect
Actually is:
![imagen](https://user-images.githubusercontent.com/66505715/139727929-a5e53e18-f8a8-4181-bdb0-09e1e086bfcb.png)
Should be:
![imagen](https://user-images.githubusercontent.com/66505715/139728473-3705de1f-024b-403b-b890-d675a1a2faf2.png)
5. The form doesn't looks centered, I have checked and the form container is centered, but the content is not ocupping the 100% of the width.
![imagen](https://user-images.githubusercontent.com/66505715/139728032-02c58ca4-e90f-48ac-82ee-0c82fc514cf5.png)
![imagen](https://user-images.githubusercontent.com/66505715/139728204-6dfc99ed-905f-4aca-9c54-ece832b39c53.png)
Please add `width: 100%` instead `width: 90%` to the input and the button (or simply erase width style and use a `display: block`)

**Comment by Israel-Laguan** [comment]
On point number 4 I think is better to be blue/purple, yellow is not good for contrast/accessibility.

**Comment by heliomar-pena** [comment]
@Israel-Laguan Thanks for clarify, I have deleted it task already

**Comment by Israel-Laguan** [comment]
On point number 5 I think design is not clear on inputs. @Katsu08 can you check if most instances of Form Inputs on design are flat?

**Comment by heliomar-pena** [comment]
@Israel-Laguan I found these inputs that in mobile / desktop are flat

1.
![imagen](https://user-images.githubusercontent.com/66505715/139728898-41a78d50-98a4-4a5c-a742-61dbb0ec3995.png)
https://xd.adobe.com/view/c94ee522-180f-487f-b7e0-90754a4b6169-9c1d/screen/3db5ef63-11f0-495d-a172-bfe7b64bb33a

2.
![imagen](https://user-images.githubusercontent.com/66505715/139729009-09f88f3f-d46f-4617-aa3b-89772d23ee71.png)
https://xd.adobe.com/view/c94ee522-180f-487f-b7e0-90754a4b6169-9c1d/screen/deea6623-62be-4cad-8b14-6d702eda2607

**Comment by Israel-Laguan** [comment]
Great, thanks for confirm, so we have to change the [Input](https://github.com/Azordev/dasher-user/blob/dev/src/components/Input.jsx) and adapt the style

**Comment by Israel-Laguan** [comment]
Current state:
https://dev--azordev-dasher-user.netlify.app/check

<img width="870" alt="image" src="https://user-images.githubusercontent.com/36519478/140770921-c2f6ccb6-c838-4b3c-9351-0a1413c1c019.png">


Will close this Issue and any other detail will be treated as a separate bug
