### ISSUE TITLE
Check Page in Desktop mode doesn't looks like the design

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#118]
**Describe the bug**
I have checked and the Check view have some differences with the design

**To Reproduce**
Go to https://dev--azordev-dasher-user.netlify.app/check

**Expected behavior**
I have listed the bugs here:

1. The hand image is hidden at the bottom. I have notice that actually doesn't exist a way to put the image at the bottom, because the image have a transparent space at the bottom that then we need hidden using a negative bottom (Actually it say `bottom: -38px`, but it value is wrong for my screen, please check screenshot 1.).  So the solution is edit the image to delete it transparent space, since the image is resizing depending of the screen and the transparent space too is resizing, therefore the actual `bottom: -38px` work for the screen of someone, but not for my screen.
2. The "Hola!" "Ingresa el número de boleta" text is not at the position expected. (Please check screenshot 2).
3. All text is more small that in the design. Please add a Media query to change the font size for desktop.

**Screenshots**

1. The hand image is hidden at the bottom. Please edit the image to delete transparent bottom image and change `bottom: -38px` for `bottom: 0px`
It looks so on my screen
![imagen](https://user-images.githubusercontent.com/66505715/139733055-b445eab8-fad9-4226-b352-e7ef44992099.png)
This is the transparent bottom space that have the image, please delete it editing the image
![imagen](https://user-images.githubusercontent.com/66505715/139733744-705bc3f5-75c7-4d25-85de-cbd8e31976e4.png)
2. The "Hola!" and "Ingresa el número de boleta" text is not at the position expected
Actually is:
![imagen](https://user-images.githubusercontent.com/66505715/139734267-7ca01db8-7886-4a7c-a93a-d01fd3ed2cda.png)
Should be:
![imagen](https://user-images.githubusercontent.com/66505715/139734283-88fd3846-3833-45ac-ac2d-a1384ca5d86f.png)
Please re positioning it and delete the `line-height` in both tags element.
3. All text are more small that in the design
Actually is:
![imagen](https://user-images.githubusercontent.com/66505715/139734821-36ecb46b-8221-4ad5-92b2-576b186efaec.png)
Should be:
![imagen](https://user-images.githubusercontent.com/66505715/139734847-a945236d-b44b-4fc5-98bd-450153d48306.png)

**Comment by Israel-Laguan** [comment]
Current state:
https://dev--azordev-dasher-user.netlify.app/check

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/36519478/140770334-96ff6fe6-903f-4c71-b045-9443750c23ee.png">

Will close this Issue and any other detail will be treated as a separate bug
