### ISSUE TITLE
Map Page in Mobile mode doesn't looks like the design

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#119]
**Describe the bug**
I have checked and the Map Page have some differences with the design

**To Reproduce**
Go to https://dev--azordev-dasher-user.netlify.app/delivery/test

**Expected behavior**
- [x] 1. At the header, only the title should have font bold. Please check image 1
- [x] 2. The footer is not ocupping width 100%, in the mobile design the footer is occuping 100%. Please check image 2
- [x] 3. The footer background color is not the primary apk color. Please check image 3
- [x] 4. The yellow text is using a rgb custom color instead of use the var secondary. Please check image 4
- [x] 5. The body background color is a custom RGB color instead the var secondary. Please check image 5
- [x] 6. Footer text colors are inverted. Please check image 6

**Screenshots**
1. Please notice that "vamos con tu envio" is bold in the actually and in the design it is not, i think is more readable how in the design
Page:
![imagen](https://user-images.githubusercontent.com/66505715/139738446-b5112f18-6769-4e89-b9b2-aec84f737c55.png)
Design:
![imagen](https://user-images.githubusercontent.com/66505715/139738480-de1707ae-5e61-4086-8aed-9d2727c7520b.png)
2. The footer is not ocupping width 100%
Actually:
![imagen](https://user-images.githubusercontent.com/66505715/139739439-585daf61-3bba-4892-9c19-e7857fcfca5d.png)
Should be:
![imagen](https://user-images.githubusercontent.com/66505715/139739460-c07769e2-a425-42a1-afc2-44c656ee2153.png)
3. I have notice that in the background color you have used a rgb custom color instead use the var primary:
Actual color: 
![imagen](https://user-images.githubusercontent.com/66505715/139739957-f02c31c6-74c5-44e2-996f-13da21f02db7.png)
That you should use:
![imagen](https://user-images.githubusercontent.com/66505715/139740006-bf78f02a-511a-4143-89de-de7b83f47947.png)
4. I have notice that in the yellow text color you have used a rgb custom color instead of use the var secondary:
You are using:
![imagen](https://user-images.githubusercontent.com/66505715/139740180-07263eab-e21e-494a-ae53-ca00b3743198.png)
You should use:
(similar to: `color: var(--secondary)`
![imagen](https://user-images.githubusercontent.com/66505715/139740210-08af5ac7-dce6-4672-8f47-f8039d705c18.png)
5. I have notice that the background of body is a custom RGB instead the var secondary. Please change it for the variable:
![imagen](https://user-images.githubusercontent.com/66505715/139740428-0930d994-3905-4021-b599-fb11ef13ce7f.png)
`background: var(--secondary)`
6. Footer text color are inverted
Please notice that the 25 (the time) should be yellow, and the bottom text should be white, and in the page is upside down
At the page:
![imagen](https://user-images.githubusercontent.com/66505715/139741711-351deb59-6d4e-45af-abfc-79c72aa46033.png)
At the design:
![imagen](https://user-images.githubusercontent.com/66505715/139741657-743ce995-76bf-4ded-b373-d600cf430b4c.png)

**Comment by heliomar-pena** [comment]
@Israel-Laguan I doesn't have added the map difference because I don't know if is a bug, please confirm. In the design, the map is occupying 100% of height and width and in the page is not.

Page
![imagen](https://user-images.githubusercontent.com/66505715/139741117-1f50517d-cebd-471b-bc31-42dedda5c348.png)
Design
![imagen](https://user-images.githubusercontent.com/66505715/139741126-6b79e311-c253-4b6e-84dd-79a74aa5633f.png)

Please confirm if is a bug or is good how it's actually

**Comment by Israel-Laguan** [comment]
> In the design, the map is occupying 100% of height and width, and the page is not.

I think it needs a media query

**Comment by Israel-Laguan** [comment]
On point number 1 the text should be dependant on the `state` of the package, we need a switch or IF...ELSE block to handle that

**Comment by heliomar-pena** [comment]
> On point number 1 the text should be dependant on the `state` of the package, we need a switch or IF...ELSE block to handle that

I undenstand, thanks for clarify. Please only check the title and subtitle font style

Design: Only the title is bold
![imagen](https://user-images.githubusercontent.com/66505715/139742137-4c907944-b6d6-49d5-a64a-656d81b49980.png)
Page: Title and subtitle are bold
![imagen](https://user-images.githubusercontent.com/66505715/139742174-fdca00c7-1c8d-4528-9f8b-3552eb16947d.png)

**Comment by Israel-Laguan** [comment]
@Katsu08 please check again as some changes was introduced, but not sure if the issue was solved in completion

**Comment by heliomar-pena** [comment]
@Israel-Laguan I will say this points are not completed, are important points?

5. I have notice that the background of body is a custom RGB instead the var secondary. Please change it for the variable:
 ![imagen](https://user-images.githubusercontent.com/66505715/139740428-0930d994-3905-4021-b599-fb11ef13ce7f.png)
`background: var(--secondary)`

6. Footer text color are inverted
        Please notice that the 25 (the time) should be yellow, and the bottom text should be white, and in the page is upside down
        At the page:
        ![imagen](https://user-images.githubusercontent.com/66505715/139741711-351deb59-6d4e-45af-abfc-79c72aa46033.png)
        At the design:
        ![imagen](https://user-images.githubusercontent.com/66505715/139741657-743ce995-76bf-4ded-b373-d600cf430b4c.png)

On the other hand, map view looks very good now!

**Comment by Katsu08** [comment]
I have encountered a new bug, its in desktop mode and the header now is not centered:

![imagen](https://user-images.githubusercontent.com/66505715/140395247-7bbad406-e3b7-45c5-bbe8-79d3fb18cc19.png)

It looks good in mobile < 600px screen. 

![imagen](https://user-images.githubusercontent.com/66505715/140395467-69bdc284-6a83-4fc9-83ec-cca10ccc292b.png)

I will open other Issue for this

**Comment by Katsu08** [comment]
> I have encountered a new bug, its in desktop mode and the header now is not centered:

I have opened a issue for this #125

**Comment by Israel-Laguan** [comment]
> @Israel-Laguan I will say this points are not completed, are important points?
> 
> 1. I have notice that the background of body is a custom RGB instead the var secondary. Please change it for the variable:
>    ![imagen](https://user-images.githubusercontent.com/66505715/139740428-0930d994-3905-4021-b599-fb11ef13ce7f.png)
>    `background: var(--secondary)`
> 2. Footer text color are inverted
>    Please notice that the 25 (the time) should be yellow, and the bottom text should be white, and in the page is upside down
>    At the page:
>    ![imagen](https://user-images.githubusercontent.com/66505715/139741711-351deb59-6d4e-45af-abfc-79c72aa46033.png)
>    At the design:
>    ![imagen](https://user-images.githubusercontent.com/66505715/139741657-743ce995-76bf-4ded-b373-d600cf430b4c.png)

Should be addressed, please include in work to do

**Comment by heliomar-pena** [comment]
Please check too this other related issue #125 #126

**Comment by heliomar-pena** [comment]
> Should be addressed, please include in work to do

@Israel-Laguan I have changed Expected Behavior to a checklist to remark the tasks that are not done and I will notify the devs

> **Expected behavior**
> 
>     * [x]  1. At the header, only the title should have font bold. Please check image 1
> 
>     * [x]  2. The footer is not ocupping width 100%, in the mobile design the footer is occuping 100%. Please check image 2
> 
>     * [x]  3. The footer background color is not the primary apk color. Please check image 3
> 
>     * [x]  4. The yellow text is using a rgb custom color instead of use the var secondary. Please check image 4
> 
>     * [ ]  5. The body background color is a custom RGB color instead the var secondary. Please check image 5
> 
>     * [ ]  6. Footer text colors are inverted. Please check image 6

**Comment by heliomar-pena** [comment]
@Azordev/dasher this issue still needs help
