### ISSUE TITLE
Add functionality to BackBtn component

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#121]
### Explication
In some views exists a BackBtn component, it's a Back arrow, with the text "Atrás" in desktop and without this in mobile.

### Screenshots
![imagen](https://user-images.githubusercontent.com/66505715/139902130-07c635f9-d3b2-438b-885b-2f391bc5ce92.png)
![imagen](https://user-images.githubusercontent.com/66505715/139902225-85fbbab7-d3b8-491a-aa07-f01d8656e42c.png)

### Checklist
 This issue can be closed when the following tasks are complete:
 
 - [x] #120 
 - [x] When user clicks BackBtn it is redirected to the previous page
 - [x] If is anything in the History, user should be redirected to delivery/:id if id is present, else return to check view
 - [x] When user is using a desktop screen, he can see the "Atrás" text
 - [x] When user is in mobile, "Atrás" text is hidden
 
### References
[Mobile design](https://xd.adobe.com/view/c94ee522-180f-487f-b7e0-90754a4b6169-9c1d/screen/70fa64b6-de96-4c98-b934-77504dc10b22/)
[Desktop design](https://xd.adobe.com/view/c94ee522-180f-487f-b7e0-90754a4b6169-9c1d/screen/70fa64b6-de96-4c98-b934-77504dc10b22/)
 
#### Related issues
- #120

**Comment by heliomar-pena** [comment]
>     * [ ]  When user clicks BackBtn it is redirected to the previous page

Please confirm if is good @Israel-Laguan @denisosuna ?

**Comment by Israel-Laguan** [comment]
> > ```
> > * [ ]  When user clicks BackBtn it is redirected to the previous page
> > ```

I confirm is the desired behavior. Also check if there is something in History, else return to delivery/:id if id is present, else return to check, to avoid problems when opening a link directly, like copy paste the link so you don't have previous site on History

**Comment by heliomar-pena** [comment]
>     * [ ]  If is anything in the History, user should be redirected to delivery/:id if id is present, else return to check view

Good job. I have added you requeriment to the checklist. If something is wrong please let me know, or change it

**Comment by denisosuna** [comment]
i will be working on this
