### ISSUE TITLE
Map Page: The clickable zone of some elements are occuping more space than they require

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#126]
**Describe the bug**
Actually if a user clicks in somewhere of this red rectangles, the event of the icon will handle

![imagen](https://user-images.githubusercontent.com/66505715/140397253-92f2f6bd-d54d-4eaf-86df-29fd033cf76f.png)

I was waiting that the zone that call the event to be the green rectangle only. While more big to be the screen, more big is the red rectangle

Here is some example:

![imagen](https://user-images.githubusercontent.com/66505715/140397785-0da7a570-4748-4196-b172-b2f75832a12b.png)
![imagen](https://user-images.githubusercontent.com/66505715/140397860-28a6f3be-7e27-48e7-a608-69eb04727679.png)

Please change the event only to the element and not to the container, or exists a reason to have the event at the container?

**To Reproduce**
1. Go to https://deploy-preview-122--azordev-dasher-user.netlify.app/delivery/test

**Expected behavior**
I was waiting that the event only to be handled if I clicks at the Icon

### Checklist

- [ ] Move the event to the children item instead of use the event at the container

**Comment by heliomar-pena** [comment]
@denisosuna Do you think you can help we with this issue?

**Comment by denisosuna** [comment]
> @denisosuna Do you think you can help we with this issue?

yes @Katsu08, I will be working on this issue
