### ISSUE TITLE
Chat View: The header is decentralized

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#127]
**Describe the bug**
Checking the chat view, I notice that the header is actually decentralized in the chat view, this happen in Desktop and Mobile view. I will left examples on the screenshots section

**To Reproduce**
1. Go to https://deploy-preview-122--azordev-dasher-user.netlify.app/chat/test

**Expected behavior**
Desktop: Text is more center
Mobile: Dasher Photo is to the left and text is center

**Screenshots**
Mobile:
![imagen](https://user-images.githubusercontent.com/66505715/140398634-8ea16677-7ae4-4aab-b166-573470f82ece.png)

Desktop:
![imagen](https://user-images.githubusercontent.com/66505715/140398656-050e8b96-fab6-4951-8a8b-999e27c2c84c.png)

### Checklist

- [x]  Fix the align of the header items in Chat View

**Comment by heliomar-pena** [comment]
The checklist is checked, someone has worked on this issue already? @Azordev/dasher

**Comment by Katsu08** [comment]
@Azordev/dasher
