### ISSUE TITLE
Add Rating modal is not showing stars on Mozilla Firefox

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#129]
**Describe the bug**
I'm enter in https://dev--azordev-dasher-user.netlify.app/confirm/test and the stars aren't showing in Mozilla, but the HTML tags yes are

**To Reproduce**
1. Go to https://dev--azordev-dasher-user.netlify.app/confirm/test using Mozilla Firefox

**Expected behavior**
The stars are showed and I can select anyone star

**Screenshots**
How u can see in the screenshot, at the right i can see the HTML elements. But at the left I can't see the stars
![imagen](https://user-images.githubusercontent.com/66505715/140573298-ad6e7749-329e-4eaf-ac80-31aa3e91e50a.png)

The img elements have a size of 32px * 0px
![imagen](https://user-images.githubusercontent.com/66505715/140573499-7489454b-714c-4aa3-8383-a3db8318c6ad.png)

I have notice that you're using content to add the image at the CSS code. Maybe Mozilla don't is flexible with this property and only accept it for pseudo elements (it's the only case of use mentioned at [MDN documentation](https://developer.mozilla.org/es/docs/Web/CSS/content) about content). What if you try using background-image or similar instead?

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Mozilla Firefox 
 - Version 94.0.1 (64-bit)

**Comment by Israel-Laguan** [comment]
Verified and works fine
