### ISSUE TITLE
Add Loader in HTML with CSS

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#13]
We can add a loader to have a more native look in mobile, but also looks nice in desktop.

## Checklist
- [ ] Upon opening the app, it have a loader like this:

![image](https://user-images.githubusercontent.com/36519478/134831898-771ed0ac-e2a2-4c7e-ab9b-aa5649f933bb.png)

**Comment by AlejandroSalcido** [comment]
Hi, i have a little doubt about how we are going to handle this?
i was thinking in someway to hide the logo once the document load, instead of redirect to a home page.

**Comment by Israel-Laguan** [comment]
HI!
> i was thinking in someway to hide the logo once the document load, instead of redirect to a home page.

Yes, exactly, here is a quick article on how to do it https://dev.to/germavinsmoke/how-to-create-a-page-load-animated-loader-in-react-3cen

Basically, the loader is there on the index.html file and when react is mounted the loader is gone. This looks like loader only showing at first, as desired
