### ISSUE TITLE
Map view: Add whatsapp button functionality

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#130]
### Explication
At the map view exists a button with a WhatsApp icon, this should redirect to a WhatsApp Chat. This feature should be added when the client give us the whatsapp nomber to use.

### Screenshots
Please notice the whatsapp icon to the bottom-right corner
![imagen](https://user-images.githubusercontent.com/66505715/140576089-8a6f98b1-b497-4152-9e1e-3b7d0db0e467.png)

### Checklist
 This issue can be closed when the following tasks are complete:
 
 - [ ] WhatsApp Icon is redirecting the user to WhatsApp chat

**Comment by Israel-Laguan** [comment]
This is the phone number the client gave: `(+56) 9 6247 8976`
