### ISSUE TITLE
Check view in Desktop: The input label is the same color that the background

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#135]
**Describe the bug**
The input label doesn't visible because its the same color that the background

**To Reproduce**

1. Go to https://dev--azordev-dasher-user.netlify.app/check

**Expected behavior**

- [ ] The color at Desktop screen is Blue
- [ ] The color at Mobile screen is Yellow

**Screenshots**
I can't see the text
![imagen](https://user-images.githubusercontent.com/66505715/140817130-269bacf8-674c-4ed9-b7c7-7d5f9381d551.png)
In mobile is good, but in desktop needs change to blue

**Additional context**
I'm using Mozilla Firefox

**Comment by Saikilito** [comment]
@Katsu08 @Israel-Laguan 

Would that be okay?

![image](https://user-images.githubusercontent.com/29690711/141108105-658d3d22-bf04-4d37-a0d0-f48f82384454.png)

**Comment by Saikilito** [comment]
The color yellow into mobile is not good

![image](https://user-images.githubusercontent.com/29690711/141109485-daf347ad-db52-4f1b-9900-15a2392738d5.png)


vs

![image](https://user-images.githubusercontent.com/29690711/141109389-04445b07-a892-43a1-84b3-0f2d305dc1ed.png)

vs

![image](https://user-images.githubusercontent.com/29690711/141109992-84e4f407-dfcb-49d2-9723-0169ef855ada.png)


I would vote to leave it gray in mobile

**Comment by Israel-Laguan** [comment]
> The color yellow into mobile is not good

> I would vote to leave it gray in mobile


I think we can change this, @Katsu08 any idea for the colors? I vote blueish for label, gray for placeholder

**Comment by Israel-Laguan** [comment]
> Would that be okay?
 
The issue refers to a label, please check this text that says "CONFIRMAR N° BOLETA O PEDIDO"
<img width="380" alt="image" src="https://user-images.githubusercontent.com/36519478/141121808-8b69f518-59f1-48dc-8bef-e75500eb77fd.png">

As the background is yellow AND the label is yellow, is not visible

**Comment by heliomar-pena** [comment]
@Saikilito Hello, sorry for the confusion and delay. Yes, I was referring to the label and not the placeholder. I think I should have left more screenshots. The text that is underlined here

> The issue refers to a label, please check this text that says "CONFIRMAR N° BOLETA O PEDIDO" <img alt="image" width="380" src="https://user-images.githubusercontent.com/36519478/141121808-8b69f518-59f1-48dc-8bef-e75500eb77fd.png">
> 
> As the background is yellow AND the label is yellow, is not visible

**Comment by heliomar-pena** [comment]
> 
> 
> > The color yellow into mobile is not good
> 
> > I would vote to leave it gray in mobile
> 
> I think we can change this, @Katsu08 any idea for the colors? I vote blueish for label, gray for placeholder

Blueish for label, gray for placeholder, that sounds good

**Comment by Saikilito** [comment]
ohhh! lol! I hadn't noticed, I can take this issue in such a case.
