### ISSUE TITLE
Improve the project documentation for new developers can start to work in it

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#139]
### Explication

We have thought to add new developers to Dasher project. We need update and improve the project documentation to make the project easier to understand for developers just starting out in the project. What I thinks we should drive in this documentation?

- How to run the project at first time
    1. Clone repository
    2. Install dependencies
    3. How to add environment variables (How he can get the environments keys)
    4. NPM/Yarn script to start development server
- Project tecnologies used. You can add a little description about the technologies, a little description about how is used in the project (in case of GraphQl for example, how are you doing the queries/mutations, for example), a link to the documentation in case of developer needs or want more information. Example of features used in Dasher, please if I miss someone add it:
    1. GraphQl
    2. React
    3. EsLint
- Project file structure
    1. What is each folder inside src?
    2. How we handle the React Files (I have seen that sometimes files are divided into 3)
    3. How we handle the CSS with styled components
- How to do one change
    1. Create a new branch for the feature/fix (Please specify the convention used in this repository. In some repositories is **feature**/#**issuenumber** or **fix**/#**issuenumber** ).
    2. Do the change, create a commit with a little description.
    3. Do a Lint test (Please specify the command to run eslint. If exists more test for this project please add it in the list)
    4. Do a push
    5. Do a pull request to DEV branch (or the main branch)
    6. Please assign some people qualificate to do the code review and wait for the code review / merge.

### References

- https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/
- https://www.quod.ai/post/the-ultimate-readme-for-remote-onboarding

**Comment by heliomar-pena** [comment]
@elpollo12 Can you help us with this task? Please confirm if you understand the task or if you have one question about the task then ask to me or @Israel-Laguan

**Comment by Israel-Laguan** [comment]
Some things to add or use:
**Important point:**

- folder structure and file naming
- npm scripts
- linters and precommit check
- branches, PRs and code reviews
- SASS and css helpers
- using graphql and services

**FAQ:**

- how do I create a new component?
- differences between layout, container and component. Base and derivative components
- How to edit a css style
- how to use an api or request to graphql using a query

**Comment by Israel-Laguan** [comment]
@Katsu08 please check the provided docs and re assign if needed

**Comment by heliomar-pena** [comment]
I think this is good for now. I will add an issue to move the actual documentation  https://docs.google.com/document/d/1TGESSinCKMWw-BMkWO0kiJlu8jqZjXxJ4ldqt5nVZAQ/edit to markdown file and use it on readme.md
