### ISSUE TITLE
Add ErrorBoundary component 

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#14]
Graceful error handling is an essential part of well-designed software. We should handle render-time errors. A sandbox component where sections with possible bugs will be isolated, in order to catch and log the error, and try to handle it.

## Checklist

- [x] There is an `ErrorBoundary` component available
- [ ] Any render error should submit an error log to `/error/render/user` with error stack, error message, ticket id, time
- [ ] Any render error Component should redirect to "Page 5XX" with ID and timestamp as fallback UI
- [ ] The `ErrorBoundary` is up to the Tree and catches any error as specified above

## References

- https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html
- https://www.infoworld.com/article/3604336/how-to-handle-errors-in-react.html
- https://www.smashingmagazine.com/2020/06/react-error-handling-reporting-error-boundary-sentry/

**Comment by heliomar-pena** [comment]
> ## Checklist
> * There is an `ErrorBoundary` component available
> * Any render error should submit an error log to `/error/render/user` with error stack, error message, ticket id, time
> * Any render error Component should redirects to "Page 5XX" with ID and timestamp as fallback UI
> * The `ErrorBoundary` is up to the Tree and catches any error as specified above

Checklist shouldn't be a task list? I think is a little more understandable

Example:

- [ ] There is an `ErrorBoundary` component available
- [ ] Any render error should submit an error log to `/error/render/user` with error stack, error message, ticket id, time
- [ ] Any render error Component should redirect to "Page 5XX" with ID and timestamp as fallback UI
- [ ] The `ErrorBoundary` is up to the Tree and catches any error as specified above

**Comment by AlejandroSalcido** [comment]
As i understand we are going to use ErrorBoundary as a sandbox component where sections with possible bugs will be isolated, in order to catch and log the error, and try to handle it, right?
