### ISSUE TITLE
Fix error styles at home page

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#142]
**Describe the bug**
Home page looks good on my device. But in another devices its deforming. I will describe two problems and posible solutions

1. The delivery boy image when the screen is small vertically it goes off the screen, posible solution is add max-height and min-height. I have tested and for me, looks better with: `max-height: 60vh` and `min-height: 40vh`.

2. The delivery boy is bad positioned at the page. You're using a mix of `position: absolute, margin-top: 20%, margin-bottom: -40%, transform: translateY(-80%)` to position the image. I think that if you're using **position: absolute**, the best is to use their properties (left, right, top, bottom) to position the image. Posible solution: delete `margin-top: 20%, margin-bottom: -40%, transform: translateY(-80%)` properties and change it for the `top` property. I have tested and for me, looks better with: ` top: 25%`

3. The button "Aceptar" is bad positioned at the page. Looks good on my device but in another devices with more little screen (vertically) it is hidden (it is goes off the screen). I think you can use again `position: absolute, top: 35%` to have a relation with the image. Other solution is use grid / flex to center at the end and center

**Checklist**
- [x] **Delivery boy image**: Add min and max height
- [x] **Delivery boy image**: Remove the properties `margin-top: 20%, margin-bottom: -40%, transform: translateY(-80%)` and replace with some position property (top or bottom. I prefer top because with bottom the image is down when the screen is extended)
- [x] **"Aceptar" button**: Remove `transform: translate(0%, 1100%);` and replace it for other way to positioning the button

**Screenshots**
![imagen](https://user-images.githubusercontent.com/66505715/141496446-474e9c1c-7cf6-4679-bda6-9c604855538e.png)

1. Go to https://dev--azordev-dasher-user.netlify.app/

**Comment by Israel-Laguan** [comment]
I confirm this issue is still present

**Comment by e-azocar** [comment]
I will try resolve it, but I'm not a responsive desing expert

**Comment by heliomar-pena** [comment]
@e-zocar Thanks. Don't worry. If you need something create the pull request and in the comments we will help you

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
