### ISSUE TITLE
Set all media queries to do <=1024px a mobile view

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#145]
**Describe the bug**
Some mobile devices how the iPad Pro have this resolution and looks bad that the view have styles for Desktops Screens. Maybe the best is set the media queries to do the mobile view to 1024px.

**Screenshots**
This views looks bad on one iPad Pro:

The title is not aligned with the subtitle
![imagen](https://user-images.githubusercontent.com/66505715/141837549-bbabb9f7-9949-45bc-a0dc-76bea3f21205.png)

The chat is not occuping 100% the view width
![imagen](https://user-images.githubusercontent.com/66505715/150367786-e492ab86-6ead-4659-baf1-bad00ec7ac7b.png)

**Expected behavior**
This are behaviors that is expected to fix with this change of queries, if don't is fixed only changing the query, please add the needed changes to fix this problems

**Checklist**
- [ ] All screens <= 1024px are considered a Tablet/Mobile View
- [ ] All screens > 1024px are considered a Desktop View

**Additional context**
To reproduce please open the deploy page in your browser and open the browser Developer Tools, then click in responsive design view and change the view for the iPad Pro screen

**Related issues**
- #149
- #148

**Comment by Israel-Laguan** [comment]
I confirm the issue is still present, yet minimal
![image](https://user-images.githubusercontent.com/36519478/143163315-d00753c6-26a6-412c-95d2-7107e4926525.png)

notice margin-left is -5px 


![image](https://user-images.githubusercontent.com/36519478/143163387-546578b4-3110-4bd6-8c0d-a2d863f89e42.png)


https://dev--azordev-dasher-user.netlify.app/

**Comment by Israel-Laguan** [comment]
In this issue, WHERE we should add the media query? @Katsu08

**Comment by heliomar-pena** [comment]
> In this issue, WHERE we should add the media query? @Katsu08

I had think that do the change at all the project. But in general only this changes was mentioned by the client:

https://github.com/Azordev/dasher-user/issues/145
https://github.com/Azordev/dasher-user/issues/149
https://github.com/Azordev/dasher-user/issues/148

**Comment by heliomar-pena** [comment]
In fact, i think that fixing this issue is fixes the #148 and #149

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
