### ISSUE TITLE
Home: Align the "Hola!" title with the "Revisemos" subtitle on iPad Pro screen

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#148]
### Explication

When you open the Home at iPad Pro Screen the title and the subtitle looks unaligned.

### How to reproduce?

1. Enter to http://dev--azordev-dasher-user.netlify.app/ from your browser 
2. Open developer tools (inspect elements)
3. Click in Responsive Design View
4. Click in sizes menu and select iPad Pro (1024x1366)
![imagen](https://user-images.githubusercontent.com/66505715/142007525-464ca116-ece6-4f47-a534-1d32aa78d213.png)

### Screenshots
Please notice how the Hola! is more to the left and "Revisemos" is more for the right
![imagen](https://user-images.githubusercontent.com/66505715/142004588-21cb8704-3cfb-4aa1-887d-f2704297c924.png)

### Checklist

This issue can be closed when the following tasks are complete:

- [x] The text is aligned at iPad Pro screen
- [x] The text is aligned in other screen sizes

### Extra information

I think that the media query that activates the desktop styles should be after 1024px, currently it is at 1024px and that may be the size of a tablet, that's why several things look bad on the iPad Pro, since they are seen with styles of desk

**Comment by Israel-Laguan** [comment]
https://github.com/Azordev/dasher-user/issues/145#issuecomment-977454189

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
