### ISSUE TITLE
Chat: Looks weird in iPad Pro screen

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#149]
### Explication

The chat view in iPad Pro looks how the desktop view, and is weird because bubble message is not occuping 100% of the screen, back button and profile picture is some big and text is little.

### Screenshots

![imagen](https://user-images.githubusercontent.com/66505715/142010268-1d8c5464-4253-4baa-8357-7f2759f5e056.png)

### Checklist

This issue can be closed when the following tasks are complete:

- [ ] Chat view looks how mobile design in iPad Pro screen
- [ ] Profile picture is not so big
- [ ] Back button is not so big

#### Related issues

- #148 

### Extra information

I think that the media query that activates the desktop styles should be after 1024px, currently it is at 1024px and that may be the size of a tablet, that's why several things look bad on the iPad Pro, since they are seen with styles of desk

**Comment by Israel-Laguan** [comment]
Please confirm with @angelik0828 about changes to make here

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
