### ISSUE TITLE
Modal "El dasher ha llegado": The subtitle is way down

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#150]
### Explication

"Recoja su envío" should be higher, near "El dasher ha llegado", because it causes the box symbol to be lost

### Screenshots

![imagen](https://user-images.githubusercontent.com/66505715/142020500-8553292c-2cd9-4edf-bd47-9735baa80416.png)

### Checklist

This issue can be closed when the following tasks are complete:

- [ ] The subtitle and the title aren't so separated between

### Route:

To access to this view please use the slug "/delivery/751f5ea3-f005-4dd9-b24e-5a779a208270". Example: https://dev--azordev-dasher-user.netlify.app/delivery/751f5ea3-f005-4dd9-b24e-5a779a208270

### How to reproduce:
1. Change the condition on this file to do that the modal was opened always while you work on this. (check the line 57) 
https://github.com/Azordev/dasher-user/blob/f8817d63ab0fb428d6c6b7bd633ea0838df3fd41/src/pages/Delivery/index.jsx#L55-L63
2. Go to your local environment, example `localhost/delivery/751f5ea3-f005-4dd9-b24e-5a779a208270`

**Comment by ildebr** [comment]
How do I get to this view?

**Comment by Fredyild** [comment]
Cordial Saludo, hay posibilidad de participar en esta tarea?

**Comment by heliomar-pena** [comment]
Saludos @Fredyild. Soy Víctor de la reunión de ayer. Sí claro, la tarea está disponible y la puedes tomar si quieres!. Es muy posible que te surjan algunas dudas sobre como empezar y si quieres nos avisas a @Israel-Laguan y a mí y nos reunimos para resolver dudas

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
