### ISSUE TITLE
Modal "Que tal tu experiencia": Customer changes

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#151]
### Explanation

The client left some comments about the design of the modality "How about your experience?"

### Screenshots

![imagen](https://user-images.githubusercontent.com/66505715/142022351-33185be9-7738-45f8-acf9-17d189bbbccf.png)

### Checklist

This issue can be closed when the following tasks are completed:

- [x] Please change the position of the subtitle and title, put the subtitle on the top and the title under the subtitle
- [x] The subtitle is not so separated 
- [x] The subtitle have a stronger color
- [x] The subtitle is bolder

**Comment by angelik0828** [comment]
Check comments, title and subtitle were changed, please tell me
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=35%3A57 
Experience view

**Comment by e-azocar** [comment]
The new modal is very good, I like it a lot

**Comment by Israel-Laguan** [comment]
I left a comment regarding the color of the text @angelik0828 please check

**Comment by angelik0828** [comment]
ok reviewed and resolved.

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
