### ISSUE TITLE
Review better ways to handle the package

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#152]
Actually we handle the package by the package ID passing it through the URL. The question is, exists better ways to handle the package ID?

The options are:

- Refactor it to use package name, you would have to refactor chat. The advantage are that the user can recognize easily the package by the URL, and back to the page using the history
- Keep using package ID and show the package name in the title. The advantage are: The user can recognize easily the package by the URL, chat view doesn't need refactor
- Save the package ID in the session storage / local storage and use package name in the URL. The advantage are: The user can recognize easily the package by the URL and chat view doesn't need refactor. 

I would like to know your opinion team

**Comment by Israel-Laguan** [comment]
@denisosuna do you think is easy to use package-code, or maybe we stick with using local session/storage?

**Comment by e-azocar** [comment]
I think the second option is the best to do this. But I wait for the opinions of others

**Comment by denisosuna** [comment]
The refactor to use the name of the package is simple and showing the code of the package would be more descriptive for the user, on the second option we would need to use helmet  to show the name of the package in the title,  I think the third option will be the easier to apply so no refactor is needed.

Another option is to pass both Id and package code as parameters in URL.

**Comment by Israel-Laguan** [comment]
The Third option is OK for me, any objections to deciding on this one @Azordev/dasher ?

**Comment by e-azocar** [comment]
The third option is ok. But, why we need save the info in localstorage?

**Comment by heliomar-pena** [comment]
The third option is ok for me.

**Comment by e-azocar** [comment]
So, the third option

**Comment by Israel-Laguan** [comment]
@Katsu08 please add a new issue with the decision we made
