### ISSUE TITLE
Confirm view: Add error or informative message when "Confirmar Recepcion" button fails

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#153]
### Explication

In confirm view (https://dev--azordev-dasher-user.netlify.app/confirm/902b7f07-da34-4ab5-9a8c-d9db03ba55b5) when user clicks confirm button and the package is already confirmed before, any action occurs, please add one message error or informative to say this to the user

### Screenshots

![imagen](https://user-images.githubusercontent.com/66505715/142036150-cf68d5ab-f1fe-499d-bde7-758a4c20a872.png)

### Checklist

This issue can be closed when the following tasks are complete:

- [ ] When package can't be confirmed, please show a message explaining what is the problem

**Comment by e-azocar** [comment]
What's the name, RUT and phone number that i need for confirm?

**Comment by Israel-Laguan** [comment]
> What's the name, RUT, and phone number that I need to confirm?

Its extra info the client knows, but in fact we only check RUT

**Comment by Israel-Laguan** [comment]
Confirm with @angelik0828 about the style for errors

**Comment by heliomar-pena** [comment]
@Israel-Laguan I think that the question is what is the information that we need put in the form to confirm that we have receive the package.

I remember that the test package have your data:

Nombre: Israel Laguan
RUT: ???
Celular: ???

Can you provide this information to @e-azocar can see the problem of this issue in local ?

**Comment by Israel-Laguan** [comment]
> Can you provide this information to @e-azocar can see the problem of this issue in local ?

I can sync up with @e-azocar on this next meeting

**Comment by angelik0828** [comment]
Rut = unique identity document in Chile, for companies and individuals, refers to a unique tax role.

**Comment by angelik0828** [comment]
When the user fills out the form, it is better to perform the validation before sending the data so we reduce errors, we can add a validator in each text field or a check and we use the pop-up window for the correct delivery validation. What do you think?
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Untitled?node-id=0%3A1

**Comment by heliomar-pena** [comment]
Other error to validate is when the package doesn't exists on the database. I notice that at the URL you can pass 'cualquier cosa'

![imagen](https://user-images.githubusercontent.com/66505715/143564181-520ca5f1-82a5-4a63-8577-1c9ae92fbb53.png)

and doesn't exists previous validation

**Comment by Israel-Laguan** [comment]
> we can add a validator in each text field or a check

Yes, what would an error message look like?

**Comment by angelik0828** [comment]
Updated bugs in figma link including the BD, tell me please.

**Comment by Israel-Laguan** [comment]
I left a question on the design @angelik0828, please check
