### ISSUE TITLE
Investigate ts-check error: "Property 'x' does not exist on type 'any []'" in Delivery/index.js

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#156]
### Screenshots

https://github.com/Azordev/dasher-user/blob/dccbce3b5b6ea8af657388eec98dfaac7b201ff9/src/pages/Delivery/index.jsx#L31-L33

https://github.com/Azordev/dasher-user/blob/dccbce3b5b6ea8af657388eec98dfaac7b201ff9/src/pages/Delivery/index.jsx#L44-L47

![img](https://user-images.githubusercontent.com/61360270/142056460-e70ad01a-5fe9-415f-859a-ef61a4b6920b.png)

### Checklist

- [ ] The reason why the error occurs is known
- [ ] Possible solutions were created
- [ ] It was decided between fixing the error or leaving it like that

**Comment by Israel-Laguan** [comment]
This can be solved adding proper types on JSDocs

In this cases adding @return types for `useGetPackageInformation` could help
![image](https://user-images.githubusercontent.com/36519478/142573152-55b9fc5a-eecb-498f-948f-66636180bedc.png)

This is an example:

```js
/**
 * @param {packageID} Id coming from DB for certain package
 * @return { {loading: Boolean, error:Object, packageInformation: Object}}
 */
const useGetPackageInformation = packageID => {
   ...
   return {loading, error, packageInformation}
}
```

In this case we would need @typedef to type the return packageInformation as expected: 
https://jsdoc.app/tags-typedef.html

Some references:

- https://devhints.io/jsdoc
- https://www.inkoop.io/blog/a-guide-to-js-docs-for-react-js/

**Comment by Israel-Laguan** [comment]
BUT, at the end this should be low priority, if it gets too weird is better to ignore these types

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
