### ISSUE TITLE
Fix pages/Confirm/index.js ts-check errors

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#157]
### Screenshots

https://github.com/Azordev/dasher-user/blob/dccbce3b5b6ea8af657388eec98dfaac7b201ff9/src/pages/Confirm/index.jsx#L1
![img](https://user-images.githubusercontent.com/61360270/142059256-d05e13fa-3e00-494a-bc3c-048341b68aea.png)
![img](https://user-images.githubusercontent.com/61360270/142059261-622c716f-2faf-481d-97d7-9e6a3863c260.png)

### Checklist

- [x] The reason why the error occurs is known
- [ ] 
- [ ] Possible solutions were created
- [ ] It was decided between fixing the error or leaving it like that

**Comment by Israel-Laguan** [comment]
This was solved in #165 / #162 please confirm @e-azocar

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels

**Comment by e-azocar** [comment]
This was already solved

**Comment by heliomar-pena** [comment]
Thanks @e-azocar
