### ISSUE TITLE
Investigate ts-check error: "Cannot find name 'isEqual'" at src/hooks/useClientLocationjs

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#159]
### Screenshots

![img](https://user-images.githubusercontent.com/61360270/142058729-03756238-00d4-4d51-8529-5b17be2a261c.png)
https://github.com/Azordev/dasher-user/blob/dccbce3b5b6ea8af657388eec98dfaac7b201ff9/src/hooks/useClientLocation.js#L60-L63

### Checklist

- [ ] The reason why the error occurs is known
- [ ] Possible solutions were created
- [ ] It was decided between fixing the error or leaving it like that

### References

https://github.com/Azordev/dasher-user/pull/154#discussion_r751258775

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
