### ISSUE TITLE
Improve the way we handle the Form and FormInputs

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#160]
### Explanation
There are some problems with the actual way to handle Form, one of the problems is with ts-check. The idea is to solve these problems with this new solution.

This issue is to discuss about the new way to handle form. Next I will add a new issue to implement the decision

### Checklist

- [ ] We have decided how to handle the form at the issues comments
- [ ] The new solution to avoid ts-check errors
- [ ] The new issue is opened

### References

https://github.com/Azordev/dasher-user/pull/154#discussion_r751255517

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels

**Comment by e-azocar** [comment]
I think that this form handling is not correct, but to solve it can be a lot of effort
