### ISSUE TITLE
Fix ts-check errors in src/components/BackButton.js

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#161]
### Explication

Please remove this ts-nocheck and solve the next problems

https://github.com/Azordev/dasher-user/blob/dccbce3b5b6ea8af657388eec98dfaac7b201ff9/src/components/BackButton/BackButton.js#L1

### Screenshots

![imagen](https://user-images.githubusercontent.com/66505715/142470474-3cb8172c-246f-472a-9e76-64ca4c9d8118.png)
![imagen](https://user-images.githubusercontent.com/66505715/142470491-dfb76094-cd14-4144-a588-1b0ab6a5a879.png)

### Checklist
This issue can be closed when the following tasks are complete:

- [x] BackBtn is receiving the text as Children directly instead of use a prop
- [x] The line 7 is individually ignore with @ts-ignore
https://github.com/Azordev/dasher-user/blob/dccbce3b5b6ea8af657388eec98dfaac7b201ff9/src/components/BackButton/BackButton.js#L7

### References

https://github.com/Azordev/dasher-user/pull/154#discussion_r751254342

**Comment by Israel-Laguan** [comment]
Text should be passed as children, directly inside

**Comment by e-azocar** [comment]
The problem is that prop. Directly passing as children works correctly

**Comment by heliomar-pena** [comment]
Thanks for the comments, i have update the issue @Israel-Laguan @e-azocar

**Comment by e-azocar** [comment]
I just needed this line
![image](https://user-images.githubusercontent.com/61360270/142491511-4c13fc7d-2fe9-4baa-9f88-0cc4bd01126f.png)

**Comment by Israel-Laguan** [comment]
> I just needed this line ![image](https://user-images.githubusercontent.com/61360270/142491511-4c13fc7d-2fe9-4baa-9f88-0cc4bd01126f.png)

This can be done in the cases we don't know types, is that ok for you @e-azocar ?

**Comment by e-azocar** [comment]
> > I just needed this line ![image](https://user-images.githubusercontent.com/61360270/142491511-4c13fc7d-2fe9-4baa-9f88-0cc4bd01126f.png)
> 
> This can be done in the cases we don't know types, is that ok for you @e-azocar ?

I think that we can use "any" as a type

**Comment by Israel-Laguan** [comment]
> I think that we can use "any" as a type

if its an object is ok with me, but if the type is easy to infer maybe adding the type is better
