### ISSUE TITLE
Help with the Report Buttom Implementation.

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#175]
### Description

need to add a link to the Node documentation
### Checklist
need to add a link to the Node documentation
Checklist
- [ ] The modal layout was added to DASHER USER
- [ ] The dev team has been talking about Dasher User NEEDS a report button. It is thought that it can be added where the user adds the RUT, but it is still necessary to design a modal where the user can write the reason for the report. Any doubt or change present it in the comments, please.

### References

- Mobile: https://xd.adobe.com/view/c94ee522-180f-487f-b7e0-90754a4b6169-9c1d/screen/3db5ef63-11f0-495d-a172-bfe7b64bb33a/
- Desktop: https://xd.adobe.com/view/b9a29d6f-091e-47d3-8769-14f54102d9e1-ecf1/screen/818cd19f-32c4-4372-a945-03c6144dc533/
- https://github.com/Azordev/dasher-user/discussions/80

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels

**Comment by Israel-Laguan** [comment]
It will be closed until client confirm to advance
