### ISSUE TITLE
Define list of Layouts

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#18]
As I see layouts in design are

## Splitted

Used in `home`, `check` and ´confirm´, you can check is composed of

- A common or parent div. For example in `home` you can add a common background.
- Left/Top Div. It is blue and in mobile is rounded.
- Right/Bottom Div. Can have yellow or white BG.

- [x] #32

## Map

Similar or derived from Splitted

- [x] #33

## Chat

Is basically one column

- [x] #34

---

Am I missing something else?

**Comment by AlejandroSalcido** [comment]
I think those layouts are right, also the main difference between spliced and map layouts, is that the second one have more components on its header and footer but it is pretty similar in general terms

**Comment by Israel-Laguan** [comment]
Closed due to inactivity. Seems like everyone is happy with these layouts
