### ISSUE TITLE
Text gets covered by hand illustration

### ISSUE THREAD

**Issue by ildebr** [Azordev/dasher-user#185]
**Describe the bug**
Text gets covered by hand illustration on ticket check

**To Reproduce**

1. Go to /check
2. Set a window size of 1090 width and 513px height for example

**Screenshots**
![localhost_3000_check](https://user-images.githubusercontent.com/73916430/147964806-c892fac2-8713-44bc-bd09-4da089aa2f97.png)

**Desktop (please complete the following information):**

- OS: windows
- Browser chrome

**Comment by Israel-Laguan** [comment]
I suggest the text have a "blueish" background and have a z-index superior to the image. This way the text can be above the image if needed, and the background makes it readable. If not above image the background wont be noticeable.

What do you think @angelik0828 ?
