### ISSUE TITLE
Image not centered and growing too much exponentially

### ISSUE THREAD

**Issue by ildebr** [Azordev/dasher-user#186]
**Describe the bug**
The dasher image of a delivery boy is aligned to left and gets bigger affecting the layout

**To Reproduce**

1. Go to landing site
2. Set the window width as less than 750px

**Screenshots**
![localhost_3000_check (2)](https://user-images.githubusercontent.com/73916430/147966087-dd762650-6244-433a-90a1-cd1b707d72e3.png)

**Additional context**

**Comment by Israel-Laguan** [comment]
So what should be good, adding a `max-width`? @angelik0828 what do you think?

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
