### ISSUE TITLE
Logo image affecting layout

### ISSUE THREAD

**Issue by ildebr** [Azordev/dasher-user#187]
**Describe the bug**
The logo image affects the layout on certain widths

**To Reproduce**

1. Go to landing page
2. Set, for example, width as 1300px width and 460px height

**Expected behavior**
I believe a good behavior for this would be for it to have a m

**Screenshots**
![localhost_3000_check (4)](https://user-images.githubusercontent.com/73916430/147967717-d36404f2-02f2-4ac6-a0c8-9ba073264fae.png)

**Comment by ildebr** [comment]
![localhost_3000_check (4)](https://user-images.githubusercontent.com/73916430/147967717-d36404f2-02f2-4ac6-a0c8-9ba073264fae.png)

**Comment by samuel-vergara-leon** [comment]
check that your tasks have the corresponding labels
