### ISSUE TITLE
Define list of Shared or Base Components

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#19]
Some shared components I see are

## Button

- [x] #22

![image](https://user-images.githubusercontent.com/36519478/134856338-96100ce7-93b8-4bc7-96c1-c90086f6c3c0.png)

## Image

- [x] #23

![image](https://user-images.githubusercontent.com/36519478/134857031-db67f707-072c-4941-905a-e755dad5b94b.png)

## Text

- [x] #29

Also text in buttons, inputs, chat and forms, we have

![image](https://user-images.githubusercontent.com/36519478/134857618-1a5b39a6-0ca9-4ff1-a549-52c4db960885.png)

## Input 

- [x] #25

![image](https://user-images.githubusercontent.com/36519478/134858165-2631c4da-bf9b-4be6-9c59-8389f8c40a03.png)

## Forms

- [x] #26

![image](https://user-images.githubusercontent.com/36519478/134858373-fb83f1d0-ad10-4a2d-b133-10171b6434e9.png)

## Modal

- [x] #24

![image](https://user-images.githubusercontent.com/36519478/134858602-2161ce29-5d85-4f64-a23d-70a61e3bd9b2.png)

### Counter Time

- [x] #27

![image](https://user-images.githubusercontent.com/36519478/134858839-b16e1592-fad7-429d-8a71-d2114e309e0b.png)

### Map y Markers

- [x] #28

![image](https://user-images.githubusercontent.com/36519478/134859060-3b84c0c5-e63c-4247-8b06-d9610b8495b5.png)

### Rating

- [x] #30

![image](https://user-images.githubusercontent.com/36519478/134859117-abb2e5c4-b5ad-4ed1-8333-e93c20b7d2d4.png)

### Chat and Chat Rows

- [x] #31

![image](https://user-images.githubusercontent.com/36519478/134859170-6615dcbf-70d3-458c-924e-7e347c97989f.png)

--- 

Did I miss something?

**Comment by AlejandroSalcido** [comment]
just need to add the return (back) buttons on the header to the shared components list, and i think we are done

**Comment by Israel-Laguan** [comment]
> add the return (back) buttons on the header to the shared components list

OK, will separate as a derived component, thanks for the suggestion

**Comment by denisosuna** [comment]
I think it's all covered

**Comment by Israel-Laguan** [comment]
Closed due to inactivity. Seems like everyone is happy with these components
