### ISSUE TITLE
Design artifacts HERE

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#2]
The designer decided to use Adobe XD (why not Figma, beat me), this is for keeping track of the last design available.

## Designs available (click image to follow link)

| Mobile views | Desktop Views |
| :-: | --- |
| [![mobile-preview][]][mobile-design] | [![desktop-preview][]][desktop-design] |

[mobile-preview]: https://user-images.githubusercontent.com/36519478/134763290-3c588e7e-7a3f-4498-82ff-e0557472e40e.png
[mobile-design]: https://xd.adobe.com/view/c94ee522-180f-487f-b7e0-90754a4b6169-9c1d/grid/
[desktop-preview]: https://user-images.githubusercontent.com/36519478/134763344-c5ebe239-98f0-4e2d-a96a-76a78777e11c.png
[desktop-design]: https://xd.adobe.com/view/b9a29d6f-091e-47d3-8769-14f54102d9e1-ecf1/grid

For reference, Mobile version for Delivery

https://xd.adobe.com/view/d9657590-cedd-48e2-b380-14157e8e9f90-8c36/

Admin panel draft

https://xd.adobe.com/view/f079aa52-a4e8-490a-b9e8-f9ad546d55ee-a52a/

**Comment by Israel-Laguan** [comment]
There is no tablet design so we just have to be creative to support all responsive sizes 😵‍💫

**Comment by AlejandroSalcido** [comment]
Great web and mobile content distribution, really optimal at the moment of implementation
