### ISSUE TITLE
Add pre requirements to README.md

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/dasher-user#203]
### Explanation

We have checked, and  Readme.md starts directly on "Run using `npm install` `npm start`". We think pre requirements should be added  as a new section to explain what is needed to run the project. Example: Install Node, NPM, Git

### Screenshots

![imagen](https://user-images.githubusercontent.com/66505715/150623118-1360a5bd-ce81-43e8-bc5c-25b7b0e256f4.png)

### Checklist

This issue can be closed when the following tasks are completed:

- [x] A link is needed to be added to Node's documentation
- [x] need to add a link to the Node documentation or download link to Git
- [x] Added documentation about what Git means or how to use it
- [x] Added documentation about what  Node is or how to use it

**Comment by samuel-vergara-leon** [comment]
Check if your tasks have labels.
