### ISSUE TITLE
Add Image Component

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#23]
Instances presented in Design (#2):

![image](https://user-images.githubusercontent.com/36519478/134857005-5a69d667-df0d-449e-8c78-acbf2824f3dc.png)
![image](https://user-images.githubusercontent.com/36519478/134857031-db67f707-072c-4941-905a-e755dad5b94b.png)
![image](https://user-images.githubusercontent.com/36519478/134857077-701677f9-bc7f-4a0a-b055-784829bc13b6.png)
![image](https://user-images.githubusercontent.com/36519478/134857100-ec362ce6-2441-4cc9-92f9-a31ba0f9cd9f.png)
![image](https://user-images.githubusercontent.com/36519478/134857131-faa2e371-c7c8-4305-9aad-f5672c1105eb.png)
![image](https://user-images.githubusercontent.com/36519478/134857154-95a3385a-0435-4c39-9cd1-1861fbe25cf7.png)
![image](https://user-images.githubusercontent.com/36519478/134857171-8569128b-b589-43ee-b0cc-b9760f50af4d.png)
![image](https://user-images.githubusercontent.com/36519478/134857207-95555d36-1acc-4285-bd81-053e9a8501f2.png)

Also includes Icons used
![image](https://user-images.githubusercontent.com/36519478/134857291-43aac599-9361-4d81-a95e-499f8cc9cd45.png)
![image](https://user-images.githubusercontent.com/36519478/134857321-16a71715-2caf-4b9d-aa93-c52841e42b38.png)
![image](https://user-images.githubusercontent.com/36519478/134857350-0cb3c20c-f9f4-4490-9c7d-92d0aee1d984.png)
![image](https://user-images.githubusercontent.com/36519478/134857377-7244a979-ec4f-4a5d-a282-d4dd64919b5b.png)
![image](https://user-images.githubusercontent.com/36519478/134857393-f423cf11-c72d-4c30-9cec-553b6bcd808a.png)
![image](https://user-images.githubusercontent.com/36519478/134857474-0397388c-c40a-4a41-ba33-10e726c5c61a.png)

**Comment by ginnaaceror** [comment]
Hi @Israel-Laguan where do I find high quality icons?

**Comment by ginnaaceror** [comment]
Hi, I see two chat icons:
This:
![chat](https://user-images.githubusercontent.com/76055458/135921388-0e785be3-8075-40bb-a0da-f9be0eeb0b34.png)
and this:
![Captura de Pantalla 2021-10-04 a la(s) 3 36 21 p  m](https://user-images.githubusercontent.com/76055458/135921415-4f4273e7-2561-4ce1-b36c-a0ec49be13ab.png)
@Israel-Laguan can you confirm me what is the final icon please?

**Comment by Israel-Laguan** [comment]
I prefer the second but designer says the first.

Let's go with the first one, the one with a human figure

**Comment by Israel-Laguan** [comment]
> Hi @Israel-Laguan where do I find high quality icons?

Design link for Mobile have the icons, please check
