### ISSUE TITLE
Add Form component

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#26]
![image](https://user-images.githubusercontent.com/36519478/134858253-46e1e854-c733-48d3-9294-7c3ddc04689a.png)
![image](https://user-images.githubusercontent.com/36519478/134858432-427ba670-0e9d-4fe9-bf8c-602cd256d47c.png)
![image](https://user-images.githubusercontent.com/36519478/134858291-463caabe-5738-4d15-9658-4386444b1235.png)
![image](https://user-images.githubusercontent.com/36519478/134858486-d8480cbd-cd52-46f5-9b83-f91ef0c492bc.png)
![image](https://user-images.githubusercontent.com/36519478/134858324-68444b97-befd-4a15-a442-1befe739dff7.png)
![image](https://user-images.githubusercontent.com/36519478/134858373-fb83f1d0-ad10-4a2d-b133-10171b6434e9.png)

## Related issues

- #22 
- #21 
- #25

**Comment by heliomar-pena** [comment]
Do you think these are good related issues?

- #22 
- #21 
- #25 
- #23

**Comment by Israel-Laguan** [comment]
> Do you think these are good related issues?
> 
> * [Add Image Component #23](https://github.com/Azordev/dasher-user/issues/23)

The star component is a button underneath so the image is not really a dependency.

Thank you a lot for the suggestions!

**Comment by Israel-Laguan** [comment]
Chat form is OK to leave as a separate component and is not included in this ticket

**Comment by AlejandroSalcido** [comment]
I just want to mention that i have rebuilt the form component in order to make it more efficient and reusable, please let me know what you guys think about it, and if you got any suggestion with the way i can handle the button location please let me know
