### ISSUE TITLE
Add Counter Time Component 

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#27]
Time here is set by Dasher (delivery) upon register the package using natural language (no validation needed). This info is static and can be obtained from package objects in DB

<img width="198" alt="image" src="https://user-images.githubusercontent.com/36519478/137956064-cbbb2381-1ea0-42c0-99e2-42f91a992ec6.png">

## Checklist

- [ ] There is a div with text of at least 128 characters.
- [ ] Text comes from props for estimatedTime, but below text is static
- [ ] component have CSS/style in a different file than component code if CSS lines are bigger than 20 LOC
- [ ] Component have proptypes

**Comment by heliomar-pena** [comment]
What does this component? Is how a timer? The time is reducing to reach 0? What occurs when the time is in 0?

**Comment by AlejandroSalcido** [comment]
> What does this component? Is how a timer? The time is reducing to reach 0? What occurs when the time is in 0?

It is a countdown timer  with a simple functionality, it will track the estimated time for the user to receive a package, and once it run to 0 it means that the package has arrived the destination.

**Comment by Israel-Laguan** [comment]
So we talked about this with the designer and we decided on this:

- Time here is set by Dasher (delivery) upon register the package using natural language (no validation needed)
- This info is static and can be obtained from package objects in DB


I updated the AC to explain this

**Comment by Israel-Laguan** [comment]
Designer changed the style of this, please refer to last design links.

**Comment by ginnaaceror** [comment]
> So we talked about this with the designer and we decided on this:
> 
> * Time here is set by Dasher (delivery) upon register the package using natural language (no validation needed)
> * This info is static and can be obtained from package objects in DB
> 
> I updated the AC to explain this

@Israel-Laguan ¿What is AC? sorry, I don't understand. 🧐

**Comment by Israel-Laguan** [comment]
> ¿What is AC?  🧐

Sorry for the confusing acronym. AC stands for Acceptance Criteria and usually have 3 sections in common issues:
- Description of a problem
- Requirements to solve the problem 
- A Checklist to track the solution

So AC is like what we want solved

**Comment by Israel-Laguan** [comment]
Solved in other PR
