### ISSUE TITLE
Add Map and Marker components

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#28]
![image](https://user-images.githubusercontent.com/36519478/134859060-3b84c0c5-e63c-4247-8b06-d9610b8495b5.png)

Notice: 
- there only will be 2 Markers, one for Delivery and other for Destination/User
- Doesn't add a Line component

**Comment by AlejandroSalcido** [comment]
I also suggest, to remove the rider location guideline, seems unnecessary and hard to match with the streets patterns.

**Comment by Israel-Laguan** [comment]
I started this work, only styling to fix and validate it works as expected

**Comment by denisosuna** [comment]
@Israel-Laguan this issue can be closed?
