### ISSUE TITLE
Add support for Maps

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#3]
As you can note in #2 we need maps, for this project we will try Google Maps, and we can use this issue to decide in another library.

## Checklist

- [x] App can display maps as per design
- [x] App have a marker for at least 2 positions at a given time
- [x] App can have different styles for both markers as per design
- [x] Keys/secrets are stored in `.env` file

**Comment by AlejandroSalcido** [comment]
I agree with Google maps, i think it is more accurate and precise, also google offers great documentation on how to use it.
