### ISSUE TITLE
Add Chat and Chat Row components

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#31]
![image](https://user-images.githubusercontent.com/36519478/134859170-6615dcbf-70d3-458c-924e-7e347c97989f.png)

## Related issues

- #23 
- #22 
- #25

**Comment by heliomar-pena** [comment]
Are this good related issues for this issue?

- #23 
- #22 
- #25

**Comment by AlejandroSalcido** [comment]
in my opinion i would only round the corners of the light blue container and reduce its opacity a bit, to make it a little less visible
