### ISSUE TITLE
Add Splitted Layout Component

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#32]
Used in `home`, `check` and ´confirm´, you can check is composed of

- [x] A common or parent div. For example in `home` you can add a common background.
- [x] Left/Top Div. It is blue and in mobile is rounded.
- [x] Right/Bottom Div. Can have yellow or white BG.

**Comment by heliomar-pena** [comment]
This would be a good task list for this issue?

> * A common or parent div. For example in `home` you can add a common background.
> * Left/Top Div. It is blue and in mobile is rounded.
> * Right/Bottom Div. Can have yellow or white BG.

**Comment by Israel-Laguan** [comment]
@ginnaaceror I think this layout was implemented already, can you confirm please?

**Comment by ginnaaceror** [comment]
> @ginnaaceror I think this layout was implemented already, can you confirm please?
Hi @Israel-Laguan Only in Check component. But the button looks big (see the image) and the colors are different.
![Captura de Pantalla 2021-10-12 a la(s) 8 28 07 a  m](https://user-images.githubusercontent.com/76055458/136965142-e360756c-3ee0-436e-bf53-92cf6d3abad0.png)

**Comment by ginnaaceror** [comment]
> @ginnaaceror I think this layout was implemented already, can you confirm please?

@Israel-Laguan This issue has already been resolved in https://github.com/Azordev/dasher-user/issues/89
