### ISSUE TITLE
Add support for GraphQL

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#4]
Update constantly the location of the markers in the App requires real-time capabilities, the team have decided in [Hasura's subscriptions](https://hasura.io/learn/graphql/intro-graphql/graphql-subscriptions/) so we will need GraphQL support. In the past Apollo Client has worked fine for us so we can continue using it, but there is a discussion to decide.

# Checklist

- [x] Request client and related packages are installed and don't break the app
- [x] Client can call graphQL queries
- [x] Client can call graphQL mutations
- [x] Client can call graphQL subscriptions
- [x] Client have cache configured per case using correct [cache policy](https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy) (optional at this point)

## Depends on

- #1 
- https://github.com/Azordev/dasher-user/discussions/9

**Comment by Israel-Laguan** [comment]
In a meeting with @denisosuna we decided on Apollo

**Comment by AlejandroSalcido** [comment]
I `ve watched the current code on a browser  i see some points on a map provided by google, are those points related with Hasuras Suscriptions?
Are Hasuras Suscriptions method the one that will allow the location to be live shared with the user, right?

**Comment by Israel-Laguan** [comment]
> I `ve watched the current code on a browser i see some points on a map provided by google, are those points related with Hasuras Suscriptions? Are Hasuras Suscriptions method the one that will allow the location to be live shared with the user, right?

Current location points come from a static file. In the future #20 should use Subscription to get those location points
