### ISSUE TITLE
Add Home view page

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#42]
After loading we see a message, an image, and a button to continue:

| Mobile | Desktop |
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/36519478/134831950-e50dbe9c-9db8-4a15-a1fd-49d9f5362965.png) | <img width="188" alt="image" src="https://user-images.githubusercontent.com/36519478/134831969-0c5dbc2a-7f99-4210-a6ca-961af1891a77.png"> |

Notice:
- the button's color depends on the background. 
- Desktop view have the logo on top
- Background is different due to curves composition
- More in [related discussion](https://github.com/Azordev/dasher-user/discussions/12)

Related issues:

- #12
- #22 
- #23 
- #29
- #32

**Comment by Katsu08** [comment]
Do you think this would be a good task list for this issue?

> Notice:
> 
> * the button's color depends on background.
> * Desktop view have logo on top
> * Background is different due curves composition
> * More in [related discussion](https://github.com/Azordev/dasher-user/discussions/12)

**Comment by ginnaaceror** [comment]
Hi @Israel-Laguan in the Adobe XD design the view is symmetrical, but in this ISSUE the background have a wave. Could you confirm me, please?

![Captura de Pantalla 2021-10-19 a la(s) 9 03 36 a  m](https://user-images.githubusercontent.com/76055458/137926378-fe5b40da-e2dc-4bbd-a344-d8a64a94c3e9.png)

![Captura de Pantalla 2021-10-19 a la(s) 9 04 03 a  m](https://user-images.githubusercontent.com/76055458/137926448-f4c847e6-80d0-496a-87b0-2008c2e1e51a.png)

**Comment by Israel-Laguan** [comment]
Please use the non-curved most updated version, please

**Comment by Israel-Laguan** [comment]
#116 will fix anything on this page
