### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#49]
### Explication
Add the view for the 404 error. The user will be redirected to this view when requesting a resource that does not exist

### Screenshots
![image](https://user-images.githubusercontent.com/36519478/134840367-0f82f170-c5f0-4a98-ae3f-e553ab1e00c9.png)

#### Related issues
- #23

**Comment by ginnaaceror** [comment]
@Israel-Laguan this page don't have mobile design?
I can see this component use only a background image. I'm right? 
Where is this image?

**Comment by Israel-Laguan** [comment]
> @Israel-Laguan this page don't have mobile design?

Designer added the image, please verify
