### ISSUE TITLE
Labels used in this project

### ISSUE THREAD

**Issue by Israel-Laguan** [Azordev/dasher-user#5]
The team has worked before in GitHub relying a lot on Labels to communicate intend, this documents how we will use labels, also to propose new labels or to change existing issues to adapt use cases.

| Label tag | Label short description | When to use | When not to use (do something else instead) | 
| --- | --- | --- | --- |
| `integration` | Use or connect external services or APIs | Backend related Code. API's queries or mutations, also configuration. Adds GraphQL queries or API endpoints, also requests configurations | UI needs more info about functionality (use `question` tag or open a new one or discussion) |
| `bug` | Something isn't working | This breaks the app or a basic functionality for Happy Path. You found a problem that needs immediate attention and can not be delayed. Makes this issue a High Priority Issue unless another tag modifies this state | The problem is related to linters/code styles/readability (use `refactor`) or doesn't break anything important (use `fix`) |
| `fix` | We need to change or update | An error or warning is showing that impacts some component or functionality. You found a problem that appears on the console or is known to be a performance problem. The visual style is not according to design or the client requested a visual change | The problem is bigger (use `bug`) or is related to linters/code styles/readability (use `refactor`) |
| `refactor` | Mayor changes in code that won't affect functionality | Code have readability, high complexity, or is not following code style. You found a problem in code that is not breaking anything but is decreasing readers/devs happiness/joy | Code can create performance issue (use `fix`) or you need clarification on the intended use-case (use `question`) |
| `documentation` | Improvements or additions to the documentation | A change you are adding needs to be explained or existent documentation needs updates | General comments or discussions (open a new issue or discussion with `question` tag) |
| `duplicate` | This issue or pull request already exists | You notices something is already covered in another issue or discussion | You solved the problem in another place (add a comment explaining) |
| `enhancement` | New feature or request | You have code that creates something new on this project or improves existing code | You want ideas to decide in something or want to propose a change (create a `question` tagged issue or start a discussion) |
| `logic` | Related to data moving through the components | Your code moved data through the components vertically or needs to change props or functions used | A prop has a typo or needs reorder/lint (Use `enhancement` tag) |
| `good first issue` | Good for newcomers | The issue can be solved for people not necessarily familiar with business logic and/or doesn't have a great impact if delayed | The issue is small but needed (use `fix`) or needs business logic's knowledge regardless (use `priority low`) |
| `help wanted` | Please share ideas | This issue or PR needs comments or commits from more engineers in the team or from other teams due it high complexity or because we don't have the capacity to complete | The issue is needed ASAP (use `priority high`) or team can not solve it in the foreseeable future (use `wontfix`) |
| `needs manual test` | A deploy is needed to check visually or the DB changes | Code review is not enough and more in-depth review needs to be done either by a stakeholder or other engineers acting as Quality Assurance | Review is hard and is taking too much time (use `help wanted`) or the issue is needed ASAP (use `priority high`) or team can not solve it in the foreseeable future (use `wontfix`) |
| `priority high` | Changes needed as soon as possible | Issue is needed ASAP. An issue or PR needs immediate action due to time or resources constraints | Code is hard and is taking too much time (use `help wanted`) or the implementation is confusing (add comments or open a discussion) or the team can not solve it in the foreseeable future (use `wontfix`) |
| `priority low` | Minor changes without much importance | Code can wait for | Code is not needed at all or you think the issue is not relevant to this project (just close the issue) or the issue is not within scope (use `wontfix`) |
| `priority medium` | Changes to make with the normal rhythm | You need to change a lower or higher priority state | You need clarifications (comment or add a discussion) |
| `question` | Further information is requested | You need clarification on the intended use-case of certain component/code/feature | You want to talk/discuss (open a discussion) or want to propose (use `enhancement`) |
| `waiting for reviewer`| PR is waiting for code / manual review | Code is complete but any review yet.  You created a PR and a day (24 h) have passed without review | Less than 24h have passed since PR creation (use `priority high` or `needs review`) |
| `wontfix` | This will not be worked on | A feature requested is not within the scope or requires extra resources not available but there is a chance to do it if someone can help. This makes the issue Medium State Issue until another tag modifies the state | You have doubts (Add comments or start a discussion) or you think the issue is not relevant to this project (just close the issue) |
| `WIP` | You already took this issue and is a work in progress | You have a branch on your machine and started to add code to solve the issue | You think you have a solution but no code on your side (use `enhancement`) or want to clarify some point (use `question`) |
| `invalid` | This doesn't seem right | You reviewed a PR and found code is not solving | You want to talk/discuss (open a discussion) or want to propose (use `enhancement`) |

**Comment by heliomar-pena** [comment]
What do you think about use:

`waiting for reviewer` instead `review waiting for reviewer` when one PR is waiting for code / manual review

`waiting for response` when one issue of type `question` or `help wanted` has not yet been answered later of 24h

**Comment by Israel-Laguan** [comment]
> `waiting for reviewer` instead `review waiting for reviewer` when one PR is waiting for code / manual review

I changed the label to be shorter, thanks for suggestion

> `waiting for response` when one issue of type `question` or `help wanted` has not yet been answered later of 24h

To me, if an issue doesn't have activity and reached High State private message is the only solution. But will keep in mind your recommendation, thanks
